### ISSUE TITLE
frontend support

### ISSUE THREAD

**Issue by Reversive** [Reversive/pe-lang#1]
#### Description
Add both lexical and syntactic analysis for the language.

#### Tasks
- [X] Add support for relational operators (LT, GT, EQ, NEQ, LEQ, GEQ)
- [X] Add type-hinting (#2)
- [X] Add assign support (=) (#3)
- [X] Add built-in functions (peopen, print, etc) (#4)
- [X] Add support for logical operators (AND, OR, NOT) (#5)
- [X] Add semi-colon support (;) (#6)
- [x] Add conditional flow structure (IF-ELSEIF-ELSE) (#9)
- [X] Add while flow structure (#10)
- [X] Add for flow structure (#11)
- [X] Add forEach flow structure (#12)
- [X] Add main entrypoint (#13)
- [X] Add vector support (#14)
- [X] Add structure member support (e.g. pe.sections) (#15)
- [X] Add tests (#16)
