### ISSUE TITLE
frontend enhancements

### ISSUE THREAD

**Issue by Reversive** [Reversive/pe-lang#19]
- [X] Change member production to accept `property` token so `member` is unique (#20)
- [X] Remove `identifier` and `string` rules so as they are not unitary (#20)
- [X] Refactor FOR clause to reduce complexity (#20)
- [X] Separate `directory_entries.imports` into `directory_entries`, `.` and `imports` (#20)
- [X] #17 

- Credits to [@agustin-golmar](https://github.com/agustin-golmar/)
